src/Entity/Project.php
<?php

namespace App\Entity;

use App\Repository\ProjectRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProjectRepository::class)
 */
class Project
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    private \DateTime $start_date;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private string $name;

    /**
     * @var int
     * @ORM\Column(type="integer")
     */
    private int $price_sold;

    /**
     * @var Type
     * @ORM\ManyToOne(targetEntity=Type::class)
     * @ORM\JoinColumn(name="type_id", referencedColumnName="id", nullable=false)
     */
    private Type $type;

    /**
     * @var int|null
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $estimatedTimeToCompletion;

    /**
     * @var int|null
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $spentTime;

    /**
     * @var Technology
     * @ORM\ManyToOne(targetEntity=Technology::class)
     * @ORM\JoinColumn(name="technology_id", referencedColumnName="id", nullable=false)
     */
    private Technology $technology;

    /**
     * @var Company
     * @ORM\ManyToOne(targetEntity=Company::class)
     * @ORM\JoinColumn(name="company_id", referencedColumnName="id", nullable=false)
     */
    private Company $company;

    /**
     * @var Collection
     * @ORM\ManyToMany(targetEntity=Worker::class)
     * @ORM\JoinTable(name="project_x_worker",
     *     joinColumns={@ORM\JoinColumn(name="project_id", referencedColumnName="id")},
     *     inverseJoinColumns={@ORM\JoinColumn("worker_id", referencedColumnName="id")}
     * )
     * @ORM\OrderBy({"name"="ASC"})
     */
    private Collection $workers;

    public function __construct()
    {
        $this->name = '';
        $this->workers = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param int $id
     * @return Project
     */
    public function setId(int $id): Project
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getStartDate(): \DateTime
    {
        return $this->start_date;
    }

    /**
     * @param \DateTime $start_date
     * @return Project
     */
    public function setStartDate(\DateTime $start_date): Project
    {
        $this->start_date = $start_date;
        return $this;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return Project
     */
    public function setName(string $name): Project
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return int
     */
    public function getPriceSold(): int
    {
        return $this->price_sold;
    }

    /**
     * @param int $price_sold
     * @return Project
     */
    public function setPriceSold(int $price_sold): Project
    {
        $this->price_sold = $price_sold;
        return $this;
    }

    /**
     * @return Type
     */
    public function getType(): Type
    {
        return $this->type;
    }

    /**
     * @param Type $type
     * @return Project
     */
    public function setType(Type $type): Project
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getEstimatedTimeToCompletion(): ?int
    {
        return $this->estimatedTimeToCompletion;
    }

    /**
     * @param int|null $estimatedTimeToCompletion
     * @return Project
     */
    public function setEstimatedTimeToCompletion(?int $estimatedTimeToCompletion): Project
    {
        $this->estimatedTimeToCompletion = $estimatedTimeToCompletion;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getSpentTime(): ?int
    {
        return $this->spentTime;
    }

    /**
     * @param int|null $spentTime
     * @return Project
     */
    public function setSpentTime(?int $spentTime): Project
    {
        $this->spentTime = $spentTime;
        return $this;
    }

    /**
     * @return Technology
     */
    public function getTechnology(): Technology
    {
        return $this->technology;
    }

    /**
     * @param Technology $technology
     * @return Project
     */
    public function setTechnology(Technology $technology): Project
    {
        $this->technology = $technology;
        return $this;
    }

    /**
     * @return Company
     */
    public function getCompany(): Company
    {
        return $this->company;
    }

    /**
     * @param Company $company
     * @return Project
     */
    public function setCompany(Company $company): Project
    {
        $this->company = $company;
        return $this;
    }

    /**
     * @return Collection
     */
    public function getWorkers(): Collection
    {
        return $this->workers;
    }

    /**
     * @param Collection $workers
     * @return Project
     */
    public function setWorkers($workers): self
    {
        $this->workers = $workers;
        return $this;
    }
    
    public function addWorker(Worker $worker): Project
    {
        if (!$this->workers->contains($worker)) {
            $this->workers->add($worker);
        }
        return $this;
    }

    public function removeWorker(Worker $worker): Project
    {
        if ($this->workers->contains($worker)) {
            $this->workers->removeElement($worker);
        }
        return $this;
    }
}

src/Controller/ProjectController.php
<?php

namespace App\Controller;

use App\Datatable\ProjectDatatableType;
use App\Entity\Project;
use App\Form\ProjectFormType;
use Doctrine\ORM\EntityManagerInterface;
use Omines\DataTablesBundle\DataTableFactory;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProjectController extends AbstractController
{
    /**
     * @param EntityManagerInterface $em
     * @return Response
     * @Route("/", name="app_project_index", methods={"get"})
     */
    public function index(EntityManagerInterface $em): Response
    {
        return $this->render('project/index.html.twig', [
            'projects' => $em->getRepository(Project::class)->findAll(),
        ]);
    }
//    public function index(Request $request, DataTableFactory $dataTableFactory): Response
//    {
//        $projectsDT = $dataTableFactory->createFromType(ProjectDatatableType::class)->handleRequest($request);
//        if ($projectsDT->isCallback()) {
//            return $projectsDT->getResponse();
//        }
//        return $this->render('project/index.html.twig', [
//            'projectsDT' => $projectsDT,
//        ];
//    }

    /**
     * @param Project $project
     * @return array
     * @Route("/project/{projectId}", name="app_project_view", methods={"get"}, requirements={"projectId"="\d+"})
     * @Entity("project", expr="repository.find(projectId)")
     * @Template("project/view.html.twig")
     */
    public function view(Project $project): array
    {
        return [
            'project' => $project,
        ];
    }

    /**
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param Project|null $project
     * @return Response
     * @Route("/project/add", name="app_project_add", methods={"get", "post"}, defaults={"mode"="add", "projectId"=0})
     * @Route("/project/{projectId}/edit", name="app_project_edit", defaults={"mode"="edit"}, requirements={"projectId"="\d+"})
     * @Entity("project", expr="repository.find(projectId)")
     */
    public function form(Request $request, EntityManagerInterface $em, ?Project $project, string $mode): Response
    {
        switch ($mode) {
            case 'add':
                $project = new Project();
                $actionPath = $this->generateUrl('app_project_add');
                break;
            case 'edit':
                $actionPath = $this->generateUrl('app_project_edit', ['projectId' => $project->getId()]);
                break;
            default:
                throw new \Exception('Mode not allowed');
        }
        $form = $this->createForm(ProjectFormType::class, $project, ['action' => $actionPath]);
        if ($request->isMethod('post')) {
            $form->handleRequest($request);
            if (!$em->contains($project)) {
                $em->persist($project);
                $em->flush();
                $em->refresh($project);
            } else {
                $em->flush();
            }
            return $this->redirectToRoute('app_project_view', ['projectId' => $project->getId()]);
        }
        return $this->render('project/form.html.twig', [
            'mode' => $mode,
            'project' => $project,
            'form' => $form->createView(),
        ]);
    }
}

templates/project/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adveris - Projet - {{ project.name }}{% endblock title %}

{% block body %}
    <h2>{% if mode == "add" %}Nouveau Projet{% else %}Projet #{{ project.id }}{% endif %}</h2>
    {{ form_start(form) }}
    <div class="card">
        <div class="card-header">
            <div class="btn-group float-end">
                <a href="{{ path("app_project_index") }}" class="btn btn-secondary">Annuler</a>
                {{ form_widget(form.submit, {attr: {class: "btn btn-primary"}}) }}
            </div>
            <h3>{% if mode == "add" %}Ajout d'un Nouveau Projet{% else %}Edition du Projet {{ project.name }}{% endif %}</h3>
        </div>
        <div class="card-body">
            {% for formName, formItem in form %}
                {% if formName not in ["submit", "_token"] %}
                    <div class="row">
                        <div class="col-2">{{ form_label(formItem, null, {attr: {class: "col-form-label"}}) }}</div>
                        <div class="col-10">{{ form_widget(formItem, {attr: {class: "form-control"}}) }}</div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    {{ form_end(form) }}
{% endblock body %}

templates/project/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adveris - Projets{% endblock title %}

{% block body %}
    <div class="float-end"><a href="{{ path("app_project_add") }}" class="btn btn-success">Ajouter</a></div>
    <h2>Projets</h2>
    <div id="projects">
        <table id="projects-table">
            <thead>
                <tr>
                    <th>{{ "project.id" | trans }}</th>
                    <th>{{ "project.startdate" | trans }}</th>
                    <th>{{ "project.name" | trans }}</th>
                    <th>{{ "project.pricesold" | trans }}</th>
                    <th>{{ "project.type" | trans }}</th>
                    <th>{{ "project.estimatedtimetocompletion" | trans }}</th>
                    <th>{{ "project.spenttime" | trans }}</th>
                    <th>{{ "project.technology" | trans }}</th>
                    <th>{{ "project.company" | trans }}</th>
                    <th>{{ "project.workers" | trans }}</th>
                    <th>Voir</th>
                </tr>
            </thead>
            <tbody>
                {% for project in projects %}
                    <tr>
                        <td>{{ project.id }}</td>
                        <td>{{ project.startDate | date("d/m/Y") }}</td>
                        <td>{{ project.name }}</td>
                        <td>{{ project.priceSold }}</td>
                        <td>{{ project.type.name }}</td>
                        <td>{{ project.estimatedTimeToCompletion }}</td>
                        <td>{{ project.spentTime }}</td>
                        <td>{{ project.technology.name }}</td>
                        <td>{{ project.company.name }}</td>
                        <td>
                            {% for worker in project.workers %}
                                {{ worker.name }}{% if not loop.last %},{% endif %}
                            {% endfor %}
                        </td>
                        <td><a href="{{ path("app_project_view", {projectId: project.id}) }}" class="btn btn-primary">Voir</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{#    <div id="projects">Loading...</div>#}
{% endblock body %}

{% block stylesheets %}
    {{ parent() }}
    <link href="//cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block javascripts %}
    {{ parent() }}
{#    <script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>#}
{#    <script>#}
{#        $(function() {#}
{#            #}{#$('#projects').initDataTables({{ datatable_settings(projectsDT) }});#}
{#        });#}
{#    </script>#}
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script>
        $(function() {
            $('#projects-table').DataTable();
        });
    </script>
{% endblock javascripts %}

templates/project/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adveris - Projet - {{ project.name }}{% endblock title %}

{% block body %}
    <h2>Projet #{{ project.id }}</h2>
    <div class="card">
        <div class="card-header">
            <div class="btn-group float-end">
                <a href="{{ path("app_project_index") }}" class="btn btn-secondary">Retour</a>
                <a href="{{ path("app_project_edit", {projectId: project.id}) }}" class="btn btn-warning">Editer</a>
            </div>
            <h3>{{ project.name }}</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-2"><b>{{ "project.id" | trans }}</b></div>
                <div class="col-10">{{ project.id }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.startdate" | trans }}</b></div>
                <div class="col-10">{{ project.startDate | date("d/m/Y") }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.name" | trans }}</b></div>
                <div class="col-10">{{ project.name }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.pricesold" | trans }}</b></div>
                <div class="col-10">{{ project.priceSold }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.type" | trans }}</b></div>
                <div class="col-10">{{ project.type.name }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.estimatedtimetocomplete" | trans }}</b></div>
                <div class="col-10">{{ project.estimatedTimeToCompletion }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.spenttime" | trans }}</b></div>
                <div class="col-10">{{ project.spentTime }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.technology" | trans }}</b></div>
                <div class="col-10">{{ project.technology.name }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.company" | trans }}</b></div>
                <div class="col-10">{{ project.company.name }}</div>
            </div>
            <div class="row">
                <div class="col-2"><b>{{ "project.workers" | trans }}</b></div>
                <div class="col-10">
                    {% for worker in project.workers %}
                        {{ worker.name }}{% if not loop.last %}<br />{% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock body %}